---
name: DateTime-Format-Japanese
version: 0.03
author:
  - |-
    Copyright (c) 2004-2006 Daisuke Maki E<lt>daisuke@cpan.orgE<gt>. 
    All rights reserved.
abstract: A Japanese DateTime Formatter
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  DateTime::Calendar::Japanese: 0.05
  DateTime::Calendar::Japanese::Era: 0.07
  DateTime::Format::Builder: 0
  Encode: 0
  Params::Validate: 0
build_requires:
  Test::More: 0
provides:
  DateTime::Format::Japanese:
    file: lib/DateTime/Format/Japanese.pm
    version: 0.03
  DateTime::Format::Japanese::Common:
    file: lib/DateTime/Format/Japanese/Common.pm
  DateTime::Format::Japanese::Traditional:
    file: lib/DateTime/Format/Japanese/Traditional.pm
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
